import SmoothScroll from '@/components/SmoothScroll.jsx'
import { Cinzel, Inter, Koulen, Roboto_Mono } from 'next/font/google'
import './globals.css'
import Overlay from '@/components/Overlay.jsx'
import Navbar from '@/components/Navbar.jsx'

const inter = Koulen({
  subsets: ['latin'],
  weight:["400"]
  
})
const roboto=Roboto_Mono({
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700"],
  variable:"--font-roboto"
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${roboto.variable}`}>
        <SmoothScroll>
          <Overlay/>
          {children}
          <Navbar/>
        </SmoothScroll>
      </body>
    </html>
  )
}
