import SmoothScroll from '@/components/SmoothScroll.jsx'
import { Cinzel, Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  
})
const roboto=Cinzel({
  subsets:["latin"],
  weight:["400","500","600","700","800","900"],
  variable:"--font-roboto"
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${roboto.variable}`}>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  )
}
